### PR TITLE
add docker support and refactor deps

### PR DESCRIPTION
**Pull request by gengjiawen**
With the help of @FX-HAO , I created with pr to support docker.
Related issue https://github.com/codeskyblue/gohttpserver/issues/27.

### CODE REVIEW

**Comment by gengjiawen** [comment]
I think we still upload to dockhub to make it more convenient to use.

**Comment by codeskyblue** [comment]
Nice

**Comment by codeskyblue** [comment]
https://hub.docker.com/r/codeskyblue/gohttpserver  I create a automated build in dockerhub.

**Comment by gengjiawen** [comment]
very good, we can update the README.md to remove local docker build.

**Pull request merged**
